# Config file for automatic testing at travis-ci.org
# References:
# https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html
#  and
#  https://github.com/jmborr/qef

dist: xenial
language: python
python:
  - 3.8

branches:
  only:
    - master
    - stable

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

install:
  - conda create -q -n testenv -c conda-forge python=$TRAVIS_PYTHON_VERSION numpy scipy flake8 pandoc
  - source activate testenv
  - pip install pytest sphinx nbsphinx sphinx_rtd_theme jupyter_client ipykernel ipywidgets bumps==0.7.12 matplotlib lmfit h5py
  # install QENSmodels

script:
  - python ./tools/Notebook_converter.py
  - python -m flake8;


notifications:
  - on_success: never
  - on_failure: never
