name: QENS models on ubuntu

on: [push, pull_request]
jobs: 
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10"]
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3.1.0
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .
      - name: lint with flake8
        run: |
            pip install flake8
            python -m flake8
      - name: mypy
        run: |
            python -m pip install mypy
            mypy ./QENSmodels/*py
      - name: run unitests
        run: |
          python -m unittest discover tests
      - name: run doctests
        run: |
          pip install pytest
          pytest --doctest-modules ./QENSmodels
      - name: build documentation
        run: |
          sudo apt install pandoc
          pip install sphinx nbsphinx sphinx_rtd_theme
          pip install  -r docs/requirements.txt
          sphinx-build -nT -b html docs docs/_build/html
          
