name: QENS models on ubuntu

on: [push, pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
      
  build:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        python-version: [3.7, 3.8, 3.9]    
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: repository
          
      - name: Set up Python
        uses: action/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r .github/workflows/requirements.txt

#       - name: Execute the notebooks
#         run: |
#           jupytext --to ipynb --execute docs/tutorials/*.py

#       - uses: actions/upload-artifact@v2
#         with:
#           name: notebooks-for-${{ github.sha }}
#           path: docs/tutorials

#       - name: Trigger RTDs build
#         uses: dfm/rtds-action@v1
#         with:
#           webhook_url: ${{ secrets.RTDS_WEBHOOK_URL }}
#           webhook_token: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
#           commit_ref: ${{ github.ref }}
