name: QENS models on ubuntu

on: [push, pull_request]
jobs: 
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3.1.0
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -c 'import sys; print(sys.version)'
      
#   build:
#     runs-on: ubuntu-latest
#     strategy: 
#       matrix:
#         python-version: [3.7, 3.8, 3.9]    
#     steps:
#       - name: checkout
#         uses: actions/checkout@v3
#         with:
#           path: repository
          
#       - name: Set up Python
#         uses: action/setup-python@v2
#         with:
#           python-version: ${{ matrix.python-version }}

#       - name: Install dependencies
#         run: |
#           python -m pip install -U pip
#           python -m pip install -r .github/workflows/requirements.txt

#       - name: Execute the notebooks
#         run: |
#           jupytext --to ipynb --execute docs/tutorials/*.py

#       - uses: actions/upload-artifact@v2
#         with:
#           name: notebooks-for-${{ github.sha }}
#           path: docs/tutorials

#       - name: Trigger RTDs build
#         uses: dfm/rtds-action@v1
#         with:
#           webhook_url: ${{ secrets.RTDS_WEBHOOK_URL }}
#           webhook_token: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
#           commit_ref: ${{ github.ref }}
